[package]
name = "ors_invitation"
version = "1.0.1"
authors = ["Hui Tang <duriantang@gmail.com>"]

[dependencies]
redis = "^0.8"

serde = "^1.0"
serde_json = "^1.0"

log = "^0.4"
env_logger = "^0.5"


dotenv = "^0.11"

clap = "^2.31"

num_cpus = "*"

nickel = "*"
nickel_cors = "*"
